package org.hinanawiyuzu.qixia.ui.theme

import androidx.compose.ui.graphics.*

val md_theme_light_primary = Color(0xFF006D44)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF91F7BD)
val md_theme_light_onPrimaryContainer = Color(0xFF002111)
val md_theme_light_secondary = Color(0xFF006C46)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF8FF7C0)
val md_theme_light_onSecondaryContainer = Color(0xFF002112)
val md_theme_light_tertiary = Color(0xFF006C4A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF8AF8C5)
val md_theme_light_onTertiaryContainer = Color(0xFF002114)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFFFF) //还是改成白色吧
val md_theme_light_onBackground = Color(0xFF002116)
val md_theme_light_surface = Color(0xFFF4FFF7)
val md_theme_light_onSurface = Color(0xFF002116)
val md_theme_light_surfaceVariant = Color(0xFFDCE5DC)
val md_theme_light_onSurfaceVariant = Color(0xFF404942)
val md_theme_light_outline = Color(0xFF717972)
val md_theme_light_inverseOnSurface = Color(0xFFBCFFE1)
val md_theme_light_inverseSurface = Color(0xFF003828)
val md_theme_light_inversePrimary = Color(0xFF75DAA3)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006D44)
val md_theme_light_outlineVariant = Color(0xFFC0C9C0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF75DAA3)
val md_theme_dark_onPrimary = Color(0xFF003921)
val md_theme_dark_primaryContainer = Color(0xFF005232)
val md_theme_dark_onPrimaryContainer = Color(0xFF91F7BD)
val md_theme_dark_secondary = Color(0xFF72DAA5)
val md_theme_dark_onSecondary = Color(0xFF003822)
val md_theme_dark_secondaryContainer = Color(0xFF005234)
val md_theme_dark_onSecondaryContainer = Color(0xFF8FF7C0)
val md_theme_dark_tertiary = Color(0xFF6EDBAA)
val md_theme_dark_onTertiary = Color(0xFF003825)
val md_theme_dark_tertiaryContainer = Color(0xFF005237)
val md_theme_dark_onTertiaryContainer = Color(0xFF8AF8C5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF002116)
val md_theme_dark_onBackground = Color(0xFF84F8CC)
val md_theme_dark_surface = Color(0xFF002116)
val md_theme_dark_onSurface = Color(0xFF84F8CC)
val md_theme_dark_surfaceVariant = Color(0xFF404942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9C0)
val md_theme_dark_outline = Color(0xFF8A938B)
val md_theme_dark_inverseOnSurface = Color(0xFF002116)
val md_theme_dark_inverseSurface = Color(0xFF84F8CC)
val md_theme_dark_inversePrimary = Color(0xFF006D44)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF75DAA3)
val md_theme_dark_outlineVariant = Color(0xFF404942)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF338A5F)
val CustomColor1 = Color(0xFF6F2642)
val light_CustomColor1 = Color(0xFF984060)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFFFD9E2)
val light_onCustomColor1Container = Color(0xFF3E001D)
val dark_CustomColor1 = Color(0xFFFFB1C8)
val dark_onCustomColor1 = Color(0xFF5E1132)
val dark_CustomColor1Container = Color(0xFF7B2949)
val dark_onCustomColor1Container = Color(0xFFFFD9E2)

val primary_color = Color(0xFF338A5F)
val secondary_color = Color(0xFF5BC28F)
val tertiary_color = Color(0xFF8AD4AF)
val neutral_color = Color(0xFFB8E3CD)

val light_background = Color(0xFFF1F6F7)
val verification_input_color = Color(0xFFF0F3F6)
val font_deep_green = Color(0xFF053B20)